import { strict as assert } from "node:assert";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = (name: string) => {
  const content = readFileSync(fileURLToPath(new URL(`../../${name}`, import.meta.url)), "utf8");
  return content.replace(/\r\n/g, "\n");
};
const deploy = root("ops/deploy.sh");
const docs = root("ops/DEPLOYMENT_HARDENING.md");
const marker = root("deploy/postgres-persistence-ready");
const packageJson = JSON.parse(root("package.json"));

assert.equal(packageJson.scripts["ops:security-audit"], "npm audit");
assert.match(deploy, /npm ci --no-audit --no-fund --foreground-scripts/);
assert.match(deploy, /NPM_CI_TIMEOUT_SECONDS="\$\{NPM_CI_TIMEOUT_SECONDS:-600\}"/);
assert.match(deploy, /flock -n 9/);
assert.match(deploy, /readlink -f.*CURRENT/);
assert.match(deploy, /check_endpoint \/api\/ready/);
assert.match(deploy, /check_endpoint \/api\/health/);
assert.match(deploy, /ROLLBACK_ATTEMPTED/);
assert.match(deploy, /git show-ref --verify/);
assert.match(deploy, /CHECK_ONLY.*-eq 0.*RELEASE_DIR.*PREVIOUS/);
assert.match(deploy, /refusing to reuse existing target release directory/);
assert.match(deploy, /refusing to overwrite existing immutable release/);
assert.equal(marker.replace(/\r\n/g, "\n"), "OFFICE_CARD_GAME_POSTGRES_PERSISTENCE_READY=1\n");
assert.match(deploy, /DB_HELPER="\/usr\/local\/sbin\/ocg-db-helper"/);
assert.match(deploy, /CUTOVER_MARKER_VALUE="OFFICE_CARD_GAME_POSTGRES_PERSISTENCE_READY=1"/);
assert.match(deploy, /npm ci --omit=dev/);
assert.doesNotMatch(deploy, /--exclude="\.\/node_modules"/);
assert.match(deploy, /node_modules\/argon2\/package\.json/);
assert.match(deploy, /node_modules\/pg\/package\.json/);
assert.doesNotMatch(deploy, /"\$DB_HELPER" enable-postgres/);
assert.doesNotMatch(deploy, /\|\| true/);
const finalize = deploy.indexOf('sudo -n "$RELEASE_HELPER" finalize "$RELEASE_NAME"');
const migrate = deploy.indexOf('sudo -n "$DB_HELPER" migrate "$RELEASE_NAME"');
const activate = deploy.indexOf('sudo -n "$RELEASE_HELPER" activate "$RELEASE_NAME"');
assert.ok(finalize >= 0 && finalize < migrate && migrate < activate);
const serviceCheck = deploy.slice(deploy.indexOf("service_is_current() {"), deploy.indexOf("verify_live() {"));
assert.match(serviceCheck, /systemctl is-active --quiet "\$SERVICE"/);
assert.match(serviceCheck, /systemctl show -p MainPID --value "\$SERVICE"/);
assert.doesNotMatch(serviceCheck, /\/proc\/\$pid\/cwd/);
assert.match(deploy, /for i in \$\(seq 1 30\)/);
assert.match(deploy, /for i in \$\(seq 1 20\)/);
const preflight = deploy.slice(deploy.indexOf("preflight() {"), deploy.indexOf("install_build_test() {"));
assert.match(preflight, /if \[\[ "\$CHECK_ONLY" -eq 1 \]\]; then/);
assert.match(preflight, /\n  fi\n  return 0\n\}/);
assert.match(docs, /npm advisory service is intentionally not on the\s+deployment-critical path/);
assert.match(docs, /deploy\.sh --check <tag>/);

console.log("Deployment hardening markers passed.");
