import { strict as assert } from "node:assert";import { readFileSync } from "node:fs";import { fileURLToPath } from "node:url";import { alphaDeckPresets } from "../src/decks.js";import { alphaDefinitions } from "../src/cards.js";import { runBalanceMatchupSet } from "../src/balance.js";
let passed=0;function test(n:string,f:()=>void){try{f();passed++;console.log(`✓ ${n}`)}catch(e){console.error(`✗ ${n}`);throw e}}
test("v7.34 seat and opener axes vary independently",()=>{const r=runBalanceMatchupSet({gamesPerMatchup:4,baseSeed:734,maxTurns:6,maxSteps:400,matchups:[{deckA:"customer-service-starter",deckB:"it-starter"}]});assert.deepEqual(r.games.map(g=>[g.p1Deck,g.firstPlayer]),[["customer-service-starter","P1"],["it-starter","P1"],["customer-service-starter","P2"],["it-starter","P2"]])});
test("v7.34 Customer Service starter remains exactly 40 cards",()=>{const d=alphaDeckPresets["customer-service-starter"];assert.equal(d.cards.reduce((n,e)=>n+e.copies,0),40)});
test("v7.34 increases Call Center Agent density",()=>{const d=alphaDeckPresets["customer-service-starter"];assert.equal(d.cards.find(e=>e.definitionId==="CS-002")?.copies,3)});
test("v7.34 removes two off-plan singleton defensive slots",()=>{const ids=new Set(alphaDeckPresets["customer-service-starter"].cards.map(e=>e.definitionId));assert.equal(ids.has("CS-015"),false);assert.equal(ids.has("N-011"),false)});
test("v7.34 leaves printed Call Center Agent stats unchanged",()=>{const c=alphaDefinitions["CS-002"];assert.equal(c.cost?.play,2);assert.equal(c.power,2)});
test("v7.34 documents two-seed directional evidence and current version",()=>{const r=readFileSync(fileURLToPath(new URL("../../README.md",import.meta.url)),"utf8");const server=readFileSync(fileURLToPath(new URL("../../server/server.mjs",import.meta.url)),"utf8");assert.match(r,/42\.9%/);assert.match(r,/41\.2%/);assert.match(server,/version: "7\.34\.0"/)});
console.log(`${passed}/6 v7.34 tests passed.`);
